[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py312"
required-version = ">=0.3.5"

[tool.ruff.lint]
select = ["F", "E", "W", "I001", "RET", "SLF001"]
ignore = ["E501"]  # Skip line length violations

[tool.ruff.format]
indent-style = "space"
quote-style = "single"
line-ending = "lf"
